/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.mihosoft.vrlfsm;

import eu.mihosoft.vrlfsm.model.*;

public class App {

    public static void main(String[] args) {
        FSM fsm = FSM.newInstance();
        
        
    }
}

