/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package eu.mihosoft.vsm.executor;

import eu.mihosoft.vsm.model.FSM;
import eu.mihosoft.vsm.model.FSMState;
import eu.mihosoft.vsm.model.State;
import eu.mihosoft.vsm.model.Transition;

import java.util.Objects;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.TimeoutException;

public class App {

    public static void main(String[] a) throws InterruptedException {

    }

}
